# Generated by Django 3.2.3 on 2021-05-19 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='numReview',
            new_name='numReviews',
        ),
    ]
